const lessons = [
    {
      id: 101,
      title: "basket ball",
      location: "Al quasis",
      price: 100,
      spaces: 5,
      icon: "fa-solid fa-basketball",
    },
    {
      id: 102,
      title: "Archery",
      location: "Ajman",
      price: 20,
      spaces: 5,
      icon: "fa-solid fa-bullseye",
    },
    {
      id: 103,
      title: "Horse Riding",
      location: "Dubai Internt CIty",
      price: 30,
      spaces: 5,
      icon: "fa-solid fa-horse",
    },
    {
      id: 104,
      title: 'Volley ball',
      location: "Deira",
      price: 25,
      spaces: 5,
      icon: "fa-solid fa-volleyball",
    },
    {
      id: 105,
      title: "Swimming",
      location: "Al Bashar",
      price: 30,
      spaces: 5,
      icon: "fa-solid fa-person-swimming",
    },
    {
      id: 106,
      title: "Cycling",
      location: "Palm Jumeirah",
      price: 20,
      spaces: 5,
      icon: "fa-solid fa-bicycle",
    },
    {
      id: 107,
      title: "Table Tennis",
      location: "Dubai International Academic City",
      price: 25,
      spaces: 5,
      icon: "fa-solid fa-table-tennis-paddle-ball",
    },
    {
      id: 108,
      title: "Painting",
      location: "Dubai Knowldege Park",
      price: 35,
      spaces: 5,
      icon: "fa-solid fa-palette",
    },
    {
      id: 109,
      title: "Programming",
      location: "Sharjah",
      price: 30,
      spaces: 5,
      icon: "fa-solid fa-code",
    },
    {
      id: 110,
      title: "Photography and Editing",
      location: "Silicon Oasis",
      price: 20,
      spaces: 5,
      icon: "fa-solid fa-camera",
    },
  ];
  