const lessons = [
    {
      id: 101,
      title: "Chroegraphy and Dancing",
      location: "Al quasis",
      price: 100,
      spaces: 5,
      icon: "bi bi-book",
    },
    {
      id: 102,
      title: "Archery and Horse Riding",
      location: "Ajman",
      price: 20,
      spaces: 5,
      icon: "bi bi-facebook",
    },
    {
      id: 103,
      title: "Car Drifting and Repair",
      location: "Dubai Internt CIty",
      price: 30,
      spaces: 5,
      icon: "bi bi-pencil",
    },
    {
      id: 104,
      title: 'Furniture making and woodworks',
      location: "Deira",
      price: 25,
      spaces: 5,
      icon: "bi bi-facebook",
    },
    {
      id: 105,
      title: "Fabrication And Welding",
      location: "Al Bashar",
      price: 30,
      spaces: 5,
      icon: "bi bi-mortarboard",
    },
    {
      id: 106,
      title: "Electrical and Repairss",
      location: "Palm Jumeirah",
      price: 20,
      spaces: 5,
      icon: "bi bi-speedometer2",
    },
    {
      id: 107,
      title: "Football and Tennis",
      location: "Dubai International Academic City",
      price: 25,
      spaces: 5,
      icon: "bi bi-hospital",
    },
    {
      id: 108,
      title: "Painting and Sculputure",
      location: "Dubai Knowldege Park",
      price: 35,
      spaces: 5,
      icon: "bi bi-bank",
    },
    {
      id: 109,
      title: "Python programming",
      location: "Sharjah",
      price: 30,
      spaces: 5,
      icon: "bi bi-shop",
    },
    {
      id: 110,
      title: "Photography and Editing",
      location: "Silicon Oasis",
      price: 20,
      spaces: 5,
      icons: "bi bi-shop",
    },
  ];
  